### ISSUE TITLE
Docker:go builder does not respect version set in manifest go_version parameter

### ISSUE THREAD

**Issue by tchardin** [testground/testground#1216]
#### Version information:

Commit: `3da7c619`

MacBook pro 2019 - Intel i9-9880H CPU @ 2.30GHz
#### Description:

I set go version to 1.16 in go.mod and manifest:
```toml
[builders."docker:go"]
enabled = true
go_version = "1.16"
```
When running the docker:go builder, build fails with message `note: module requires Go 1.16` in the daemon logs.

Thanks!
