### ISSUE TITLE
Configure TaaS to not allow any tasks other than `cluster:k8s`

### ISSUE THREAD

**Issue by nonsense** [testground/testground#1236]
At the moment we allow all kinds of jobs on TaaS. This creates various infrastructure issues, as it starts testplans on infra nodes.

We should block the Testground daemon from starting any tasks that don't use the `cluster:k8s` runner, i.e. it should not be possible for users to start `local:docker` tasks on TaaS, as all containers related to that test run would be start on a single VMs, where the daemon is running.

**Comment by brdji** [comment]
After spending a bit of time looking into this, I have a rough proposal for a solution:
1. Each runner (`k8s, local, docker`, etc.) would add the following field to its struct definition:
`Blocked bool toml:"blocked"`
2. When performing a `doRun` request, the runner should return an error if it is blocked by the config
3. Adding the blocked field to the default `env.toml` file (in the infra repo, `config-map-env-toml`) for each runner would ensure that deploying the cluster means that only the `cluster_k8s` runner is enabled.

Thoughts, suggestions?

**Comment by laurentsenta** [comment]
Sounds good to me, could we use `enabled = bool`? That would be consistent with the manifest.toml:

manifest.toml:

```toml
[runners]
"local:docker"  = { enabled = true }
"local:exec"    = { enabled = true }
"cluster:k8s"   = { enabled = true }
```

maybe env.toml:

```toml
[runners."cluster:k8s"]
enabled = true # note enabled here
run_timeout_min             = 1
testplan_pod_cpu            = "10m"
testplan_pod_memory         = "10Mi"
collect_outputs_pod_cpu     = "10m"
collect_outputs_pod_memory  = "10Mi"
autoscaler_enabled          = false
provider                    = ""
sysctls = []

[runners."local:docker"]
enabled = false # note enabled here

[daemon]
# ...
```
