### ISSUE TITLE
Add builders parameters to groups in composition files

### ISSUE THREAD

**Issue by laurentsenta** [testground/testground#1357]
## Description

Subtask for https://github.com/testground/testground/issues/1340

We're working on interoperability tests with the go & rust libp2p projects, see https://github.com/testground/testground/issues/1340 and https://github.com/testground/testground/issues/1305.

We need the ability to write a test that uses different builders (like `docker:go` and `docker:generic`).

Example of a desired composition file:

```toml
[global]
  plan = "integrations_mixed_builders"
  case = "issue-1357-mix-builder-configuration"
  total_instances = 2
  runner = "local:docker"

[[groups]]
  id = "go"
  instances = { count = 1 }
  builder = "docker:go" # override builder here

  [groups.build_config]
    path = "go/" # define base path here

  [groups.run.test_params]
    expected_implementation = "go"

[[groups]]
  id = "generic"
  instances = { count = 1 }
  builder = "docker:generic" # override builder here

  [groups.build_config]
    path = "generic/" # define base path here
    build_args = { image = "golang:1.16-buster" }

  [groups.run.test_params]
    expected_implementation = "generic"
```

## What defines this endeavor to be complete?

- [x] create a corresponding integration test with a similar manifest,
- [x] move the build configuration fields to the groups,
- [x] make sure the overrides manifest > composition.global > composition.groups are working as expected,
- [ ] have the test passing & use in libp2p.
