### ISSUE TITLE
Authentication issue when executing test on k8s

### ISSUE THREAD

**Issue by Bidon15** [testground/testground#1374]
#### Version information:
Commit: 2b3b5d92bac73cd2a78a37555de0c5b8884161bc
Client HW: Intel x86 64bit, OSX
K8s: AWS

#### Description:
1. Set up the K8s on AWS similar to what `testground/infra` has 
2. Initialise a kube config for a client under `$HOME/.kube/config`
3. Added .env.config info under default path of testground dir with info similar to https://github.com/testground/testground/blob/master/env-example.toml
4. Started test run
5. Observe this issue 
```bash
POST "https://...": x509: certificate signed by unknown authority
```

Note: in our `kube/config` we have the following structure

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <some.info>
    server: https://<domain>.amazonaws.com
  name: test.k8s.local
contexts:
- context:
    cluster: test.k8s.local
    user: test.k8s.local
  name: test.k8s.local
current-context: test.k8s.local
kind: Config
preferences: {}
users:
- name: test.k8s.local
  user:
    client-certificate-data: <some.info>
    client-key-data: <some.info>
```
