### ISSUE TITLE
Reuse existing compositions for creating new ones

### ISSUE THREAD

**Issue by Bidon15** [testground/testground#1483]
## Description
Let's say we have a `composition.toml` like this:
```toml
[global]
  plan = "foo"
  case = "bar-1"
  total_instances = 6
  builder = "docker:generic"
  runner = "local:docker"
  disable_metrics = false

[global.run.test_params]
  latency = "60"

[[groups]]
  id = "validators"
  builder = "docker:generic"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.build_config]
   ...
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    bandwidth = "256Mib"
    role = "validator"

[[groups]]
  id = "relayers"
  builder = "docker:generic"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.build_config]
   ...
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    bandwidth = "256Mib"
    role = "relayer"
```

Now, I want to create a new `composition-2.toml` based on `composition-1.toml`, where I want to have the same setup of `[[groups]]` + adding a new `[[group]]` like: 

```
[[groups]]
  id = "clients"
  builder = "docker:generic"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.build_config]
   ...
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    bandwidth = "100Mib"
    role = "client"
```

In order to achieve that - I need to copy the whole `composition-1.toml` into `composition-2.toml` + add new group to make this work 

## What defines this endeavour to be complete?

- [ ] make the testground tool understand that 1 composition is a part to another one
