### ISSUE TITLE
Composition field cascading/inheritance

### ISSUE THREAD

**Issue by raulk** [testground/testground#521]
Example:

```toml
[global.run]
test_params = { foo = 100, bar = "xyz" }
```

Test parameters defined in the global block would propagate down to all groups. Any test parameters defined in groups would override the global ones. The challenge becomes how to _UNSET_ a globally set parameter within a group, given that TOML does not support nil values 🤷‍♂️
